spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_HOST_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
#        generate_statistics: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id:  ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: ${SCOPES}

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.thymeleaf: DEBUG

server:
  port: 9091

github:
  api:
    url: https://api.github.com


app:
  admin:
    adminsHtmlPage: /admin/admins.html
    teachersHtmlPage: /teacher/teachers.html
    studentsHtmlPage: /student/students.html
    groupsHtmlPage: /group/groups.html
    coursesHtmlPage: /course/courses.html
    coursesAssignGroupFrom: /course/assign-groups-form.html
    coursesUnassignGroupForm: /course/unassign-groups-form.html
  teacher:
    dashboardHtmlPage: /teacher/dashboard.html
    labManagementHtmlPage: /teacher/lab-management.html
  student:
    dashboardHtmlPage: student/dashboard.html


testResults:
  destinationFolder: report
  zipFileName: artifact.zip
  xmlFileName: test-results.xml

queue:
  attempts: queue/attempts
  repositories: queue/repositories

